name: Deploy to GitHub Pages
run-name: ${{ github.event.pull_request.title || github.ref_name }}

"on":
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    environment: github-pages
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-pages@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: .
      - id: deploy
        uses: actions/deploy-pages@v4
